name: LFS and Regular Sync Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  TARGET_ORG: tsvi-org
  TARGET_REPO: lfs-new
  SERVICE_ACCOUNT_EMAIL: machine@acme.com
  SERVICE_ACCOUNT_NAME: machine


jobs:
  lfs_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for LFS objects
          lfs: true # Fetch Git LFS files
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure Git LFS is installed
        run: |
          if ! git lfs; then
            sudo apt-get install git-lfs
            git lfs install
          fi

      - name: Add target repository as a remote
        run: |
          git remote add target git@github.com:${{ env.TARGET_ORG }}/${{ env.TARGET_REPO }}.git
          git config --global user.email "${{ env.SERVICE_ACCOUNT_EMAIL }}"
          git config --global user.name "${{ env.SERVICE_ACCOUNT_NAME }}"

      - name: Push LFS objects to the target repository
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          # Push LFS objects to the target repository
          if ! git lfs push --all target HEAD:$branch_name; then
            echo "Failed to push LFS objects to the target repository."
            exit 1
          fi

  regular_sync:
    needs: lfs_sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
      - name: Add target repository as a remote using SSH
        run: |
          git remote add target git@github.com:${{ env.TARGET_ORG }}/${{ env.TARGET_REPO }}.git
          git config --global user.email "${{ env.SERVICE_ACCOUNT_EMAIL }}"
          git config --global user.name "${{ env.SERVICE_ACCOUNT_NAME }}"
  
      - name: Push changes to the target repository (excluding LFS objects)
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          # Push commits to the target repository
          git push target HEAD:$branch_name